-- KikiJob PostgreSQL production schema draft.
-- Target: Supabase PostgreSQL.
-- This migration is intentionally additive and does not touch local SQLite.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_provider TEXT NOT NULL DEFAULT 'local',
  auth_subject TEXT,
  name TEXT,
  email TEXT,
  phone TEXT,
  identity TEXT,
  password_hash TEXT,
  email_verified_at TIMESTAMPTZ,
  phone_verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_auth_subject_unique UNIQUE (auth_provider, auth_subject)
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique
  ON users (LOWER(email))
  WHERE email IS NOT NULL AND email <> '';

CREATE UNIQUE INDEX IF NOT EXISTS users_phone_unique
  ON users (phone)
  WHERE phone IS NOT NULL AND phone <> '';

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS auth_sessions (
  token_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  user_agent TEXT,
  ip_address INET,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS auth_sessions_user_id_idx ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS auth_sessions_expires_at_idx ON auth_sessions(expires_at);

CREATE TABLE IF NOT EXISTS email_codes (
  email TEXT PRIMARY KEY,
  code_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  name TEXT,
  email TEXT,
  phone TEXT,
  current_city TEXT,
  school TEXT,
  degree TEXT,
  major TEXT,
  graduation_date TEXT,
  education_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  experiences_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  projects_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  practice_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  skills_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  profile_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS user_profiles_set_updated_at ON user_profiles;
CREATE TRIGGER user_profiles_set_updated_at
  BEFORE UPDATE ON user_profiles
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS job_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  target_roles TEXT,
  goals JSONB NOT NULL DEFAULT '[]'::jsonb,
  locations JSONB NOT NULL DEFAULT '[]'::jsonb,
  salary_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
  industries JSONB NOT NULL DEFAULT '[]'::jsonb,
  company_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  remote_preference TEXT,
  company_size_preference TEXT,
  allow_resume_tailoring BOOLEAN NOT NULL DEFAULT TRUE,
  preference_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS job_preferences_goals_gin_idx ON job_preferences USING GIN(goals);
CREATE INDEX IF NOT EXISTS job_preferences_locations_gin_idx ON job_preferences USING GIN(locations);

DROP TRIGGER IF EXISTS job_preferences_set_updated_at ON job_preferences;
CREATE TRIGGER job_preferences_set_updated_at
  BEFORE UPDATE ON job_preferences
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  storage_path TEXT,
  file_type TEXT,
  file_size BIGINT,
  parsed_text TEXT,
  parsed_profile_json JSONB,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  parse_status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT resumes_parse_status_check CHECK (parse_status IN ('pending', 'parsed', 'failed'))
);

CREATE UNIQUE INDEX IF NOT EXISTS resumes_one_default_per_user_idx
  ON resumes(user_id)
  WHERE is_default = TRUE;

CREATE INDEX IF NOT EXISTS resumes_user_created_idx ON resumes(user_id, created_at DESC);

DROP TRIGGER IF EXISTS resumes_set_updated_at ON resumes;
CREATE TRIGGER resumes_set_updated_at
  BEFORE UPDATE ON resumes
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  company_type TEXT,
  industry TEXT,
  locations JSONB NOT NULL DEFAULT '[]'::jsonb,
  careers_url TEXT,
  logo_url TEXT,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS companies_name_unique ON companies(LOWER(name));
CREATE INDEX IF NOT EXISTS companies_company_type_idx ON companies(company_type);

DROP TRIGGER IF EXISTS companies_set_updated_at ON companies;
CREATE TRIGGER companies_set_updated_at
  BEFORE UPDATE ON companies
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
  source TEXT NOT NULL,
  source_url TEXT,
  title TEXT NOT NULL,
  company_name TEXT NOT NULL,
  location TEXT,
  salary TEXT,
  jd_text TEXT,
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  company_type TEXT,
  recruitment_type TEXT,
  channel TEXT,
  is_demo BOOLEAN NOT NULL DEFAULT FALSE,
  published_at TIMESTAMPTZ,
  deadline TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS jobs_source_url_unique
  ON jobs(source_url)
  WHERE source_url IS NOT NULL AND source_url <> '';

CREATE INDEX IF NOT EXISTS jobs_company_id_idx ON jobs(company_id);
CREATE INDEX IF NOT EXISTS jobs_location_idx ON jobs(location);
CREATE INDEX IF NOT EXISTS jobs_recruitment_type_idx ON jobs(recruitment_type);
CREATE INDEX IF NOT EXISTS jobs_deadline_idx ON jobs(deadline);
CREATE INDEX IF NOT EXISTS jobs_tags_gin_idx ON jobs USING GIN(tags);

DROP TRIGGER IF EXISTS jobs_set_updated_at ON jobs;
CREATE TRIGGER jobs_set_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS saved_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT saved_jobs_user_job_unique UNIQUE(user_id, job_id)
);

CREATE INDEX IF NOT EXISTS saved_jobs_user_id_idx ON saved_jobs(user_id);

DROP TRIGGER IF EXISTS saved_jobs_set_updated_at ON saved_jobs;
CREATE TRIGGER saved_jobs_set_updated_at
  BEFORE UPDATE ON saved_jobs
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  resume_id BIGINT REFERENCES resumes(id) ON DELETE SET NULL,
  source_url TEXT,
  submitted_at TIMESTAMPTZ,
  applied_at TIMESTAMPTZ,
  follow_up_at TIMESTAMPTZ,
  next_action TEXT,
  notes TEXT,
  submission_result TEXT,
  autofill_session_id TEXT,
  updated_source TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT applications_user_job_unique UNIQUE(user_id, job_id),
  CONSTRAINT applications_submission_result_check CHECK (
    submission_result IS NULL OR submission_result IN ('success', 'failed', 'unknown')
  )
);

CREATE INDEX IF NOT EXISTS applications_user_status_idx ON applications(user_id, status);
CREATE INDEX IF NOT EXISTS applications_follow_up_idx ON applications(follow_up_at);
CREATE INDEX IF NOT EXISTS applications_updated_at_idx ON applications(updated_at DESC);

DROP TRIGGER IF EXISTS applications_set_updated_at ON applications;
CREATE TRIGGER applications_set_updated_at
  BEFORE UPDATE ON applications
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS job_matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  resume_id BIGINT REFERENCES resumes(id) ON DELETE SET NULL,
  score INTEGER NOT NULL,
  reasons_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  risks_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  gaps_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  suggestions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  calculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS job_matches_user_job_idx ON job_matches(user_id, job_id);
CREATE INDEX IF NOT EXISTS job_matches_score_idx ON job_matches(score DESC);

CREATE TABLE IF NOT EXISTS resume_analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
  analysis_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS resume_analyses_user_resume_idx ON resume_analyses(user_id, resume_id);

CREATE TABLE IF NOT EXISTS form_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  mappings_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS form_mappings_set_updated_at ON form_mappings;
CREATE TRIGGER form_mappings_set_updated_at
  BEFORE UPDATE ON form_mappings
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS user_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS user_events_user_created_idx ON user_events(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS user_events_type_idx ON user_events(event_type);
