function entry(company, type, careersUrl, extras = {}) {
  return {
    company,
    type,
    careersUrl: careersUrl || buildOfficialRecruitSearchUrl(company),
    urlKind: careersUrl ? 'official' : 'official-search',
    industry: extras.industry || type,
    businessLine: extras.businessLine || '',
    recruitmentRoles: extras.recruitmentRoles || [],
    locations: extras.locations || [],
    friendlyTags: extras.friendlyTags || [],
    audienceTags: extras.audienceTags || [],
    entryExperience: extras.entryExperience || '',
  };
}

function buildOfficialRecruitSearchUrl(company) {
  return `https://www.bing.com/search?q=${encodeURIComponent(`${company} 校园招聘 官方 投递入口`)}`;
}

export const preferredCompanies = [
  entry('中国移动', '央国企 通信 校招 实习', 'https://job.10086.cn/', {
    industry: '通信/运营商',
    recruitmentRoles: ['产品经理', '网络工程师', '数据分析', '运营', '技术支持'],
    locations: ['北京', '上海', '广州', '深圳', '杭州', '全国'],
    audienceTags: ['本科友好'],
    entryExperience: '运营商央企，城市覆盖广，岗位稳定，适合通信、计算机、数据、产品和运营方向。',
  }),
  entry('中国电信', '央国企 通信 云计算 校招 实习', 'https://job.chinatelecom.com.cn/wt/TELE/web/index/campus', {
    industry: '通信/云计算',
    recruitmentRoles: ['云计算', 'AI产品经理', '网络工程师', '数据分析', '解决方案'],
    locations: ['北京', '上海', '广州', '深圳', '杭州', '全国'],
    audienceTags: ['本科友好'],
    entryExperience: '运营商央企，云和网络岗位多，适合希望稳定发展且关注数字化业务的同学。',
  }),
  entry('中国联通', '央国企 通信 校招 实习', 'https://chinaunicom.zhaopin.com/', {
    industry: '通信/运营商',
    recruitmentRoles: ['网络工程师', '产品经理', '运营', '数据分析', '解决方案'],
    locations: ['北京', '上海', '广州', '深圳', '杭州', '全国'],
    audienceTags: ['本科友好'],
    entryExperience: '运营商央企，分子公司选择多，岗位偏通信、政企、产品和数字化运营。',
  }),
  entry('国家电网', '央国企 能源 电力 校招', 'https://zhaopin.sgcc.com.cn/', {
    industry: '能源/电力',
    recruitmentRoles: ['电气工程师', '信息通信', '数据分析', '财务', '管理类'],
    locations: ['全国'],
    audienceTags: ['本科友好'],
    entryExperience: '电网央企，稳定性强，电气、自动化、计算机和财务方向匹配度更高。',
  }),
  entry('中国石化', '央国企 能源 化工 校招', 'http://job.sinopec.com/', {
    industry: '能源/化工',
    recruitmentRoles: ['化工工程师', '设备工程师', '安全环保', '财务', '信息化'],
    locations: ['全国'],
    audienceTags: ['本科友好'],
    entryExperience: '能源化工央企，地域覆盖广，生产、设备、化工、安全和管理岗位较多。',
  }),
  entry('中国工商银行', '央国企 银行 金融 校招 实习', 'https://job.icbc.com.cn/', { industry: '银行/金融', recruitmentRoles: ['金融科技', '管培生', '数据分析', '运营', '风险管理'], locations: ['全国'], audienceTags: ['本科友好'], entryExperience: '大行体系成熟，网点和金融科技岗位覆盖广，适合金融、计算机、数据和运营方向。' }),
  entry('中国建设银行', '央国企 银行 金融 校招 实习', 'https://job.ccb.com/', { industry: '银行/金融', recruitmentRoles: ['金融科技', '管培生', '数据分析', '运营', '产品经理'], locations: ['全国'], audienceTags: ['本科友好'], entryExperience: '国有大行，岗位稳定，金融科技、业务运营和管培方向适合应届生积累履历。' }),
  entry('中国银行', '央国企 银行 金融 校招 实习', 'https://www.boc.cn/aboutboc/bi4/', { industry: '银行/金融', recruitmentRoles: ['金融科技', '管培生', '国际业务', '数据分析', '运营'], locations: ['全国'], audienceTags: ['本科友好'], entryExperience: '国有大行，国际化业务特点明显，适合金融、语言、数据和技术方向。' }),
  entry('中国农业银行', '央国企 银行 金融 校招 实习', 'https://career.abchina.com.cn/', { industry: '银行/金融', recruitmentRoles: ['金融科技', '管培生', '运营', '数据分析', '客户经理'], locations: ['全国'], audienceTags: ['本科友好'], entryExperience: '网点覆盖广，岗位数量多，适合希望稳定就业和区域选择灵活的同学。' }),
  entry('交通银行', '央国企 银行 金融 校招 实习', 'https://job.bankcomm.com/', { industry: '银行/金融', recruitmentRoles: ['金融科技', '管培生', '数据分析', '运营', '风险管理'], locations: ['全国'], audienceTags: ['本科友好'], entryExperience: '国有大行，金融科技与业务岗位并行，适合金融、经管和计算机方向。' }),
  entry('招商银行', '银行 金融 校招 实习', 'https://career.cmbchina.com/', { industry: '商业银行/零售金融', recruitmentRoles: ['金融科技', '数据分析', '产品经理', '总行管培', '分行市场营销', '运营支持', '信息技术', '信用卡产品'], locations: ['北京', '上海', '广州', '深圳', '杭州', '合肥', '济南', '青岛'], audienceTags: ['本科友好'], entryExperience: '股份制银行龙头，多城市岗位，业务节奏更市场化，金融科技、管培和零售金融机会较多。' }),
  entry('浦发银行', '银行 金融 校招 实习', 'https://spdb.zhaopin.com/', { industry: '银行/金融', recruitmentRoles: ['金融科技', '管培生', '数据分析', '运营'], locations: ['全国'], audienceTags: ['本科友好'], entryExperience: '股份制银行，上海及多城市机会较多，适合金融和技术复合背景。' }),
  entry('兴业银行', '银行 金融 校招 实习', 'https://job.cib.com.cn/', { industry: '银行/金融', recruitmentRoles: ['金融科技', '管培生', '绿色金融', '数据分析'], locations: ['全国'], audienceTags: ['本科友好'], entryExperience: '股份制银行，绿色金融和金融科技方向可关注，岗位稳定性较好。' }),
  entry('中信银行', '银行 金融 校招 实习', 'https://job.citicbank.com/', { industry: '银行/金融', recruitmentRoles: ['金融科技', '管培生', '数据分析', '运营'], locations: ['全国'], audienceTags: ['本科友好'], entryExperience: '综合金融背景强，适合金融科技、数据分析和业务运营方向。' }),
  entry('汇丰', '外企 银行 金融 校招 实习', 'https://www.hsbc.com/careers', { industry: '银行/外企金融', recruitmentRoles: ['管培生', '金融科技', '数据分析', '风险管理', '客户运营'], locations: ['上海', '广州', '深圳', '香港', '全国'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '外资金融机构，英文环境和合规体系成熟，适合希望积累国际化金融经验的同学。' }),

  entry('华为', '大厂 通信 AI 云计算 终端 智能汽车 校招 实习', 'https://career.huawei.com/cn/campus-recruitment', { industry: 'AI/通信/云计算/智能汽车', businessLine: 'ICT、云、终端、车BU、芯片与器件', recruitmentRoles: ['AI算法', '软件开发', '产品经理', '解决方案', '数据分析'], locations: ['深圳', '北京', '上海', '杭州', '南京', '西安', '全国'], audienceTags: ['本科友好'], entryExperience: '大平台技术岗位密集，成长快但强度较高，适合技术、产品和解决方案方向。' }),
  entry('网易有道', '互联网 AI 智能硬件 教育 校招 实习', 'https://hr.youdao.com/index.php?t1=index', { industry: '互联网/人工智能/教育', businessLine: '智能教育硬件、AI学习、在线教育', recruitmentRoles: ['算法', '教育产品', '硬件研发', '运营', '市场'], locations: ['杭州', '北京', '成都'], friendlyTags: ['双非友好', '本科友好'], audienceTags: ['本科友好'], entryExperience: '互联网教育与AI硬件结合，岗位涵盖技术、产品和教育运营，节奏较互联网化。' }),
  entry('同花顺', '互联网 AI 金融科技 校招 实习', 'https://campus.10jqka.com.cn/', { industry: '互联网/人工智能/金融科技', businessLine: '金融数据、AI应用、智能投研', recruitmentRoles: ['AI算法', 'Java开发', '数据分析', '产品经理', '金融研究'], locations: ['杭州'], audienceTags: ['本科友好'], entryExperience: '金融科技垂直公司，岗位偏AI、研发和数据，适合计算机、金融复合背景。' }),
  entry('白杨智能', '互联网 AI Agent 校招 实习', '', { industry: '互联网/人工智能/大模型 Agent', businessLine: '大模型 Agent 与企业服务', recruitmentRoles: ['产品经理', '大模型Agent研发', '算法', '运营'], locations: ['北京'], audienceTags: ['本科友好'], entryExperience: 'AI创业公司，岗位靠近大模型应用，节奏快，更适合想做AI产品或应用落地的同学。' }),
  entry('腾讯', '互联网 大厂 AI 校招 实习', 'https://join.qq.com/', { industry: '互联网/大厂', recruitmentRoles: ['产品经理', '运营', '算法工程师', '前端开发', '后端开发', '数据分析'], locations: ['深圳', '北京', '上海', '广州', '成都'], audienceTags: ['本科友好'], entryExperience: '大厂平台和业务线多，适合技术、产品、运营、数据等方向，竞争强。' }),
  entry('阿里巴巴', '互联网 大厂 电商 AI 校招 实习', 'https://talent.alibaba.com/', { industry: '互联网/电商/云计算', recruitmentRoles: ['产品经理', '算法工程师', '后端开发', '运营', '商业分析'], locations: ['杭州', '北京', '上海', '深圳'], audienceTags: ['本科友好'], entryExperience: '电商、云和本地生活等业务线丰富，岗位多但筛选竞争强。' }),
  entry('蚂蚁集团', '金融科技 大厂 AI 校招 实习', 'https://talent.antgroup.com/', { industry: '金融科技/互联网', recruitmentRoles: ['金融科技', '算法工程师', '数据分析', '产品经理', '风险管理'], locations: ['杭州', '上海', '北京'], audienceTags: ['本科友好'], entryExperience: '金融科技场景强，适合技术、风控、数据和产品方向。' }),
  entry('字节跳动', '互联网 大厂 AI 校招 实习', 'https://jobs.bytedance.com/campus/', { industry: '互联网/AI/内容平台', recruitmentRoles: ['产品经理', '运营', '算法工程师', '数据分析', '后端开发'], locations: ['北京', '上海', '深圳', '杭州', '广州'], audienceTags: ['本科友好'], entryExperience: '业务增长和AI应用岗位密集，节奏快，适合产品、技术、运营、数据方向。' }),
  entry('火山引擎', '互联网 大厂 云计算 AI 校招 实习', 'https://jobs.bytedance.com/campus/', { industry: '云计算/AI/企业服务', recruitmentRoles: ['云计算', 'AI产品经理', '后端开发', '解决方案', '数据分析'], locations: ['北京', '上海', '杭州', '深圳'], audienceTags: ['本科友好'], entryExperience: '字节企业服务与云计算方向，适合AI云、解决方案、产品和研发方向。' }),
  entry('美团', '互联网 大厂 本地生活 校招 实习', 'https://career.meituan.com/', { industry: '互联网/本地生活', recruitmentRoles: ['产品经理', '运营', '数据分析', '算法工程师', '后端开发'], locations: ['北京', '上海', '成都', '深圳'], audienceTags: ['本科友好'], entryExperience: '本地生活场景多，岗位贴近业务，适合产品、运营、数据和技术方向。' }),
  entry('百度', '互联网 大厂 AI 校招 实习', 'https://talent.baidu.com/jobs/list?projectType=1', { industry: '互联网/AI/搜索', recruitmentRoles: ['AI算法', '产品经理', '数据分析', '后端开发', '运营'], locations: ['北京', '上海', '深圳'], audienceTags: ['本科友好'], entryExperience: 'AI和搜索技术积累强，适合算法、产品、研发和数据方向。' }),
  entry('携程', '互联网 大厂 旅游 校招 实习', 'https://pages.ctrip.com/commerce/promote/201108/other/hire/process.html', { industry: '互联网/旅游', recruitmentRoles: ['产品经理', '数据分析', '运营', '后端开发', '商业分析'], locations: ['上海'], audienceTags: ['本科友好'], entryExperience: '在线旅游业务成熟，上海岗位集中，适合产品、运营、数据和技术方向。' }),
  entry('京东', '互联网 电商 大厂 校招 实习', 'https://campus.jd.com/', { industry: '互联网/电商/物流', recruitmentRoles: ['产品经理', '供应链', '运营', '后端开发', '数据分析'], locations: ['北京', '上海', '深圳', '成都'], audienceTags: ['本科友好'], entryExperience: '零售和供应链场景丰富，适合技术、产品、运营、供应链方向。' }),
  entry('快手', '互联网 内容 大厂 校招 实习', 'https://campus.kuaishou.cn/', { industry: '互联网/内容平台', recruitmentRoles: ['产品经理', '运营', '算法工程师', '数据分析', '后端开发'], locations: ['北京', '杭州', '深圳'], audienceTags: ['本科友好'], entryExperience: '短视频和直播业务成熟，适合内容产品、运营、推荐算法和数据方向。' }),
  entry('小红书', '互联网 内容 社区 大厂 校招 实习', 'https://job.xiaohongshu.com/campus', { industry: '互联网/内容社区', recruitmentRoles: ['产品经理', '运营', '商业分析', '算法工程师', '数据分析'], locations: ['上海', '北京'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '内容社区和消费场景明显，适合产品、运营、商业化和数据方向。' }),
  entry('哔哩哔哩', '互联网 内容 大厂 校招 实习', 'https://jobs.bilibili.com/campus', { industry: '互联网/内容平台', recruitmentRoles: ['产品经理', '运营', '游戏运营', '前端开发', '数据分析'], locations: ['上海', '北京'], audienceTags: ['本科友好'], entryExperience: '内容社区调性强，适合内容运营、产品、技术和商业化方向。' }),
  entry('网易', '互联网 游戏 大厂 校招 实习', 'https://campus.163.com/', { industry: '互联网/游戏', recruitmentRoles: ['游戏策划', '游戏运营', '产品经理', '客户端开发', '数据分析'], locations: ['杭州', '广州', '上海'], audienceTags: ['本科友好'], entryExperience: '游戏和互联网业务线多，适合游戏、产品、运营、研发方向。' }),
  entry('米哈游', '互联网 游戏 大厂 校招 实习', 'https://campus.mihoyo.com/', { industry: '互联网/游戏', recruitmentRoles: ['游戏策划', '游戏运营', '客户端开发', '美术', '数据分析'], locations: ['上海'], audienceTags: ['本科友好'], entryExperience: '游戏研发和内容制作特色强，适合游戏策划、技术、美术和运营方向。' }),

  entry('欧莱雅', '外企 女性友好 快消 美妆 校招 实习', 'https://careers.loreal.com/', { industry: '快消/美妆', recruitmentRoles: ['品牌市场', '市场营销', '运营', '电商', '供应链'], locations: ['上海', '广州', '全国'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '美妆外企，品牌和市场岗位成熟，适合市场、运营、电商、供应链方向。' }),
  entry('雅诗兰黛', '外企 女性友好 美妆 校招 实习', 'https://www.elcompanies.com/en/careers', { industry: '快消/美妆', recruitmentRoles: ['品牌市场', '市场营销', '电商', '运营', '供应链'], locations: ['上海'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '美妆外企，品牌矩阵丰富，适合市场、电商和消费者运营方向。' }),
  entry('资生堂', '外企 女性友好 美妆 校招 实习', 'https://corp.shiseido.com/en/careers/', { industry: '快消/美妆', recruitmentRoles: ['品牌市场', '市场营销', '运营', '电商'], locations: ['上海'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '美妆外企，品牌和零售场景明显，适合市场、运营、电商方向。' }),
  entry('宝洁', '外企 女性友好 快消 校招 实习', 'https://www.pgcareers.com/', { industry: '快消/日化', recruitmentRoles: ['品牌市场', '销售管培', '供应链', '数据分析', '财务'], locations: ['广州', '上海', '北京'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '快消外企，管培和品牌体系成熟，适合市场、销售、供应链和数据方向。' }),
  entry('联合利华', '外企 女性友好 快消 校招 实习', 'https://careers.unilever.com/', { industry: '快消/日化', recruitmentRoles: ['品牌市场', '销售', '供应链', '电商', '财务'], locations: ['上海', '广州', '全国'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '快消外企，品牌、渠道和供应链岗位体系成熟，工作规范化程度高。' }),
  entry('LVMH', '外企 女性友好 奢侈品 美妆 校招 实习', 'https://www.lvmh.com/join-us', { industry: '奢侈品/美妆/零售', recruitmentRoles: ['品牌市场', '零售运营', '电商', '供应链', '商业分析'], locations: ['上海', '北京', '广州'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '奢侈品集团，品牌与零售岗位多，适合市场、零售运营和商业分析方向。' }),
  entry('香奈儿', '外企 女性友好 奢侈品 美妆 校招 实习', 'https://www.chanel.com/cn/careers/', { industry: '奢侈品/美妆/零售', recruitmentRoles: ['零售运营', '品牌市场', '客户体验', '电商'], locations: ['上海', '北京', '广州'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '奢侈品品牌，岗位偏零售、品牌和客户体验，适合服务意识强的同学。' }),
  entry('宜家', '外企 女性友好 零售 校招 实习', 'https://www.ikea.com/global/en/our-business/how-we-work/work-with-us/', { industry: '零售/家居', recruitmentRoles: ['零售运营', '供应链', '电商', '市场营销', '人力资源'], locations: ['上海', '北京', '广州', '深圳', '全国'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '零售外企，文化开放，适合零售运营、供应链、电商和HR方向。' }),
  entry('诺和诺德', '外企 女性友好 医药 校招 实习', 'https://www.novonordisk.com/careers.html', { industry: '医药/外企', recruitmentRoles: ['医学事务', '市场准入', '数据分析', '运营', '管培生'], locations: ['北京', '上海', '天津'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '医药外企，合规体系成熟，适合医学、药学、市场和数据方向。' }),
  entry('强生', '外企 女性友好 医药 快消 校招 实习', 'https://www.careers.jnj.com/', { industry: '医药/消费健康', recruitmentRoles: ['市场营销', '医学事务', '销售管培', '供应链', '数据分析'], locations: ['上海', '北京', '广州'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '医疗健康外企，业务线多，适合医学、市场、销售和供应链方向。' }),
  entry('玛氏', '外企 女性友好 快消 校招 实习', 'https://careers.mars.com/', { industry: '快消/食品', recruitmentRoles: ['市场营销', '销售管培', '供应链', '财务', '人力资源'], locations: ['广州', '上海', '北京'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '快消外企，宠物护理和食品业务成熟，适合市场、销售、供应链方向。' }),
  entry('雀巢', '外企 女性友好 快消 校招 实习', 'https://www.nestle.com/jobs', { industry: '快消/食品', recruitmentRoles: ['市场营销', '销售', '供应链', '质量', '财务'], locations: ['北京', '上海', '广州'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '食品快消外企，岗位稳定，适合市场、销售、供应链和质量方向。' }),
  entry('微软', '外企 科技 大厂 校招 实习', 'https://jobs.careers.microsoft.com/', { industry: '科技/软件/AI', recruitmentRoles: ['软件开发', 'AI算法', '产品经理', '云计算', '数据分析'], locations: ['北京', '上海', '苏州'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '科技外企，工程文化成熟，适合软件、AI、云和产品方向。' }),
  entry('苹果', '外企 科技 大厂 校招 实习', 'https://jobs.apple.com/', { industry: '科技/硬件/零售', recruitmentRoles: ['软件开发', '硬件工程师', '运营', '零售管理', '供应链'], locations: ['上海', '北京', '深圳'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '硬件与零售并重，岗位规范，适合技术、供应链和零售运营方向。' }),
  entry('亚马逊', '外企 科技 大厂 校招 实习', 'https://www.amazon.jobs/', { industry: '科技/电商/云计算', recruitmentRoles: ['软件开发', '产品经理', '数据分析', '运营', '供应链'], locations: ['北京', '上海', '深圳'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '国际化科技公司，岗位偏技术、运营和供应链，英文环境加分。' }),
  entry('特斯拉', '外企 新能源 制造 校招 实习', 'https://www.tesla.cn/careers/search/', { industry: '新能源/汽车/制造', recruitmentRoles: ['制造工程师', '质量工程师', '供应链', '数据分析', '销售运营'], locations: ['上海', '北京', '深圳'], audienceTags: ['本科友好'], entryExperience: '新能源车企，制造和运营节奏快，适合工程、供应链和质量方向。' }),
  entry('SAP', '外企 科技 软件 校招 实习', 'https://jobs.sap.com/', { industry: '科技/软件/企业服务', recruitmentRoles: ['软件开发', '顾问', '数据分析', '产品经理', '云计算'], locations: ['上海', '北京', '大连'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '企业软件外企，工作规范，适合软件开发、咨询和数据方向。' }),
  entry('IBM', '外企 科技 软件 校招 实习', 'https://www.ibm.com/careers/', { industry: '科技/软件/咨询', recruitmentRoles: ['软件开发', '咨询顾问', '数据分析', '云计算', 'AI应用'], locations: ['北京', '上海', '深圳', '大连'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '老牌科技外企，咨询和技术服务体系成熟，适合技术和顾问方向。' }),
  entry('沃尔沃', '外企 制造 汽车 校招 实习', 'https://www.volvogroup.com/en/careers.html', { industry: '汽车/制造', recruitmentRoles: ['车辆工程', '供应链', '质量', '项目管理', '数据分析'], locations: ['上海', '成都', '全国'], audienceTags: ['本科友好'], entryExperience: '制造外企，岗位偏工程、质量和供应链，流程规范。' }),
  entry('爱立信', '外企 通信 校招 实习', 'https://www.ericsson.com/en/careers', { industry: '通信/外企', recruitmentRoles: ['通信工程师', '软件开发', '网络工程师', '测试', '项目管理'], locations: ['北京', '上海', '南京', '广州'], audienceTags: ['本科友好'], entryExperience: '通信外企，适合通信、软件、网络和项目管理方向。' }),
  entry('Spotify', '外企 海外远程 校招 实习', 'https://www.lifeatspotify.com/jobs', { industry: '互联网/音频/海外', recruitmentRoles: ['产品经理', '数据分析', '软件开发', '运营'], locations: ['海外', '远程'], audienceTags: ['本科友好'], entryExperience: '海外互联网岗位，英文和远程协作要求高，适合作为海外机会关注池。' }),

  entry('麒麟信安', '互联网 AI 操作系统 网络安全 校招', '', { industry: '基础软件/网络安全', recruitmentRoles: ['软件开发', '操作系统', '网络安全', '测试'], locations: ['长沙', '北京', '广州'], audienceTags: ['本科友好'], entryExperience: '国产基础软件公司，适合系统软件、安全和测试方向。' }),
  entry('姚记科技', '互联网 游戏 金融科技 校招', '', { industry: '互联网/游戏/数字营销', recruitmentRoles: ['游戏运营', '数据分析', '市场营销', '产品经理'], locations: ['上海', '苏州'], audienceTags: ['本科友好'], entryExperience: '民企成长型公司，游戏和营销业务并行，岗位节奏较快。' }),
  entry('哈乐沃德', '互联网 游戏 校招', '', { industry: '游戏/互联网', recruitmentRoles: ['游戏策划', '游戏运营', '客户端开发', '美术'], locations: ['武汉'], audienceTags: ['本科友好'], entryExperience: '游戏公司，适合游戏策划、运营和研发方向。' }),
  entry('宝宝巴士', '互联网 儿童教育 APP 游戏 校招', '', { industry: '互联网/儿童教育/内容', recruitmentRoles: ['产品经理', '游戏策划', '动画设计', '运营', '开发'], locations: ['福州'], audienceTags: ['本科友好'], entryExperience: '儿童内容与教育产品公司，内容和产品岗位有特色，福州生活成本相对低。' }),
  entry('泛林集团', '外企 半导体 芯片 制造 校招', '', { industry: '半导体/芯片设备', recruitmentRoles: ['Field Service Engineer', 'Process Engineer', '设备工程师', '工艺工程师'], locations: ['深圳', '上海', '北京', '西安', '武汉', '无锡'], audienceTags: ['本科友好'], entryExperience: '半导体设备外企，工程服务和工艺岗位多，英文和动手能力加分。' }),
  entry('戴尔科技', '外企 半导体 IT 硬件 软件 校招', '', { industry: '电子/计算机/硬件', recruitmentRoles: ['供应链', '产品工程', '软件开发', '数据分析'], locations: ['上海', '厦门', '大连'], friendlyTags: ['女性友好'], audienceTags: ['本科友好'], entryExperience: '国际硬件与IT公司，供应链和工程岗位规范，适合英语较好的同学。' }),
  entry('汉得信息', '互联网 AI 企业数字化咨询 软件实施 校招', '', { industry: '企业数字化咨询/ERP实施', recruitmentRoles: ['Java后端开发', '全栈开发', '数据开发', '产品经理', '数字化咨询顾问'], locations: ['上海', '北京', '大连', '武汉', '广州', '全国'], audienceTags: ['本科友好', '双非友好'], entryExperience: '国内IT咨询企业，总部上海，项目制可能出差，咨询顾问成长快。' }),
  entry('紫光同芯', '半导体 芯片 集成电路 校招', '', { industry: '半导体/芯片', recruitmentRoles: ['芯片设计', '嵌入式软件', '测试工程师', '产品经理'], locations: ['北京', '成都', '上海', '深圳'], audienceTags: ['本科友好'], entryExperience: '芯片设计公司，岗位偏研发和测试，适合微电子、电子、计算机方向。' }),
  entry('星空科技', '半导体 芯片 光电 精密仪器 校招', '', { industry: '光电/精密仪器', recruitmentRoles: ['系统设计', '光学设计', '光学测试', '软件开发', '电气设计'], locations: ['上海'], audienceTags: ['本科友好', '双非友好'], entryExperience: '光电精密仪器企业，研发和技术支持岗位多，测试岗需要出差。' }),
  entry('惟丰科技', '半导体 芯片 光电 系统集成 校招', '', { industry: '光电系统/半导体设备', recruitmentRoles: ['系统工程师', '光学工程师', '电子工程师', '算法工程师', '销售精英'], locations: ['上海'], audienceTags: ['本科友好', '双非友好'], entryExperience: '光电系统企业，研发和销售并重，技术支持可能出差，中小企业成长快。' }),
  entry('催甲科技', '半导体 芯片 光电 软件 校招', '', { industry: '光学/软件/精密仪器', recruitmentRoles: ['软件工程师', '算法工程师', '光学工程师', '机械工程师'], locations: ['上海'], audienceTags: ['本科友好'], entryExperience: '光电精密方向，岗位偏研发和应用支持，适合光学、电子、机械、计算机背景。' }),
  entry('达发科技', '半导体 芯片 无线通信 校招', '', { industry: '无线通信芯片', recruitmentRoles: ['系统软件研发', '芯片验证', '嵌入式', '测试'], locations: ['苏州', '南京', '成都'], audienceTags: ['本科友好'], entryExperience: '无线通信芯片公司，多城市，验证和软件岗位技术氛围浓。' }),
  entry('渠梁电子', '半导体 芯片 封测 校招', '', { industry: '集成电路封测', recruitmentRoles: ['工艺工程师', '设备工程师', '质量工程师'], locations: ['泉州', '晋江'], audienceTags: ['本科友好', '双非友好'], entryExperience: '半导体封测企业，制造为主，工艺和质量体系成熟。' }),
  entry('玖锦科技', '半导体 射频微波 仪器仪表 校招', '', { industry: '射频微波/电子对抗/仪器仪表', recruitmentRoles: ['射频微波', '通信', '信号处理', '光电', '自动化'], locations: ['成都'], audienceTags: ['本科友好', '双非友好'], entryExperience: '射频微波企业，成都岗位，测试和技术支持需要进实验室。' }),
  entry('星宸科技', '半导体 芯片 校招', '', { industry: '半导体/芯片/图像处理', recruitmentRoles: ['数字IC', '算法', '软件开发', '硬件测试'], locations: ['厦门', '深圳', '上海', '武汉'], audienceTags: ['本科友好'], entryExperience: '芯片公司，影像与AIoT相关岗位较多，技术门槛较高。' }),
  entry('芯原股份', '半导体 芯片 校招', '', { industry: '半导体/IP/芯片设计', recruitmentRoles: ['数字IC', '验证', '嵌入式', '软件开发'], locations: ['上海', '南京', '成都'], audienceTags: ['本科友好'], entryExperience: '芯片IP公司，研发岗位多，适合微电子、计算机和通信方向。' }),
  entry('中信戴卡', '汽车 制造 央国企 校招', '', { industry: '汽车/智能制造', recruitmentRoles: ['车辆工程', '机械工程', '质量', '工艺', '供应链'], locations: ['秦皇岛'], audienceTags: ['本科友好'], entryExperience: '汽车零部件国企，制造与工艺岗位多，稳定性较好。' }),
  entry('TE汽车事业部中国区', '外企 汽车 智能驾驶 零部件 校招', '', { industry: '汽车连接器/传感器/智能驾驶', recruitmentRoles: ['工程研发工程师', '项目管理工程师', '质量工程师', '生产运营', '客户商务'], locations: ['苏州', '南通', '上海'], audienceTags: ['本科友好'], entryExperience: '全球连接器外企，苏州、南通、上海岗位，质量和生产岗位需跟产线，英文环境。' }),
  entry('天海集团', '汽车 制造 校招', '', { industry: '汽车/零部件', recruitmentRoles: ['工程技术', '质量', '制造', '项目管理'], locations: ['郑州', '鹤壁', '上海'], audienceTags: ['本科友好'], entryExperience: '汽车零部件企业，工程和质量岗位较多，适合机械、车辆、自动化方向。' }),
  entry('永联科技', '新能源 电力 储能 校招', '', { industry: '新能源/电力电子/储能', recruitmentRoles: ['嵌入式软件', '电力电子', '测试', '产品经理'], locations: ['深圳', '苏州'], audienceTags: ['本科友好'], entryExperience: '新能源电力电子公司，研发和测试岗位多，成长速度较快。' }),
  entry('优旦科技', '新能源 电力 AI 软件 校招', '', { industry: '新能源/电力/AI软件', recruitmentRoles: ['算法', '软件开发', 'AI产品经理', '项目实施'], locations: ['西宁'], audienceTags: ['本科友好'], entryExperience: '电力新能源软件方向，实施和售前岗位机会较多，生活成本相对低。' }),
  entry('华润燃气泰州区域公司', '央国企 能源 燃气 校招', '', { industry: '能源/燃气', recruitmentRoles: ['工程管理', '安全管理', '运营', '财务'], locations: ['泰州', '盐城'], audienceTags: ['本科友好'], entryExperience: '燃气央企区域公司，岗位稳定，工程和运营岗位适合本地发展。' }),
  entry('中国电建江西院', '央国企 电力 设计院 校招', '', { industry: '能源/电力/设计院', recruitmentRoles: ['电力设计', '土木建筑', '新能源', '水利工程'], locations: ['南昌', '广州', '西安', '长沙'], audienceTags: ['本科友好'], entryExperience: '电力设计院，设计和工程咨询岗位多，偏稳定但项目节奏较强。' }),
  entry('英维克', '机械装备 工业自动化 新能源 校招', '', { industry: '机械装备/热管理', recruitmentRoles: ['研发工程师', '电子控制', '热能', '结构', '市场'], locations: ['深圳', '苏州', '中山'], audienceTags: ['本科友好'], entryExperience: '热管理和储能温控公司，研发、制造和市场岗位都有机会。' }),
  entry('树根科技', '工业互联网 软件 AI 校招', '', { industry: '工业互联网/AI软件', recruitmentRoles: ['Java开发', '数据开发', '产品经理', '软件实施'], locations: ['广州'], audienceTags: ['本科友好'], entryExperience: '工业互联网平台，实施和研发并重，适合软件、产品和工业数字化方向。' }),
  entry('源清动力', '新能源 电力 氢能 校招', '', { industry: '新能源/氢能', recruitmentRoles: ['技术工程师', '工艺工程师', '燃料电池', '项目管理'], locations: ['江苏无锡'], audienceTags: ['本科友好'], entryExperience: '氢能与新能源公司，工程和技术岗位为主，适合能源、机械、材料方向。' }),
  entry('新时达', '智能制造 机器人 自动化 校招', '', { industry: '智能制造/机器人/自动化', recruitmentRoles: ['嵌入式软件', '电机控制', '算法', '销售工程师'], locations: ['上海', '深圳'], audienceTags: ['本科友好'], entryExperience: '自动化与机器人公司，研发和销售工程岗位都有，民企成长节奏较快。' }),
  entry('乐动机器人', '智能制造 机器人 AI 校招', '', { industry: '机器人/人工智能', recruitmentRoles: ['算法', '软件开发', '产品经理', '测试'], locations: ['深圳'], audienceTags: ['本科友好'], entryExperience: '机器人公司，岗位偏算法、软件和产品，适合想进入具身智能方向的同学。' }),
  entry('星海图', '智能制造 机器人 AI 校招', '', { industry: '机器人/人工智能', recruitmentRoles: ['算法', '机器人研发', '产品经理', '数据'], locations: ['苏州', '深圳', '北京'], audienceTags: ['本科友好'], entryExperience: '具身智能/机器人公司，适合算法、工程和产品方向。' }),
  entry('坤维科技', '智能制造 传感器 机器人 校招', '', { industry: '机器人/传感器/力控', recruitmentRoles: ['传感器研发', '嵌入式', '算法', '测试'], locations: ['北京', '常州', '扬州'], audienceTags: ['本科友好'], entryExperience: '机器人传感器方向，硬件、嵌入式和测试岗位较多。' }),
  entry('云迹科技', '智能制造 服务机器人 AI 校招', '', { industry: '服务机器人/AI', recruitmentRoles: ['算法', '软件开发', '产品经理', '实施工程师'], locations: ['北京'], audienceTags: ['本科友好'], entryExperience: '服务机器人公司，产品和实施场景明确，适合机器人应用方向。' }),
  entry('中国网安三十所', '央国企 网络安全 AI 软件 校招', '', { industry: '网络安全/信息安全', recruitmentRoles: ['技术研究', '软件开发', '网络安全', '算法', '测试'], locations: ['成都'], audienceTags: [], entryExperience: '网络安全国企研究所，学历门槛较高，适合网安、密码、软件和算法方向。' }),
  entry('易控智驾', '汽车 智能驾驶 校招', '', { industry: '汽车/智能驾驶', recruitmentRoles: ['自动驾驶算法', '仿真', '平台研发', '测试质量', '车辆工程'], locations: ['郑州', '北京'], audienceTags: ['本科友好'], entryExperience: '矿山无人驾驶企业，算法门槛较高，测试和工程岗位相对可投。' }),
  entry('零跑汽车', '汽车 新能源 智能驾驶 校招', '', { industry: '汽车/新能源/智能驾驶', recruitmentRoles: ['智驾算法', '三电算法', '软件开发', '整车研发', '供应链'], locations: ['杭州', '金华', '湖州'], audienceTags: ['本科友好', '双非友好'], entryExperience: '新势力车企，岗位类型全，制造、质量、供应链和物流方向较友好。' }),
  entry('银轮股份', '汽车 热管理 零部件 校招', '', { industry: '汽车/热管理/零部件', recruitmentRoles: ['产品研发', '技术应用', '供应链', '工艺质量', '生产管理'], locations: ['浙江台州'], audienceTags: ['本科友好', '双非友好'], entryExperience: '汽车热管理龙头，研发和制造岗位多，台州生活成本较低。' }),
  entry('中国航发黎明', '航空航天 军工 央国企 校招', '', { industry: '航空航天/军工/发动机', recruitmentRoles: ['航空发动机', '机械', '材料', '自动化', '计算机'], locations: ['沈阳'], audienceTags: [], entryExperience: '航空发动机国企，硕士起步较多，技术门槛高，稳定性强。' }),
  entry('星际天算', '航空航天 卫星互联网 校招', '', { industry: '航空航天/商业航天', recruitmentRoles: ['AI算法', '地面通信', '轨道设计', '星务软件', '载荷研发'], locations: ['上海'], audienceTags: [], entryExperience: '商业航天公司，上海岗位，研发门槛较高，团队精干。' }),
  entry('航天恒星科技有限公司', '航空航天 卫星应用 校招', '', { industry: '航空航天/卫星应用', recruitmentRoles: ['系统设计', 'FPGA', '嵌入式', '射频工程', '软件测试'], locations: ['北京', '天津', '西安', '南昌', '无锡', '成都'], audienceTags: [], entryExperience: '卫星应用国企，多城市可选，航天研发门槛较高。' }),
  entry('上海民用航空控制与导航系统有限公司', '航空航天 民航电子 校招', '', { industry: '航空航天/民航电子', recruitmentRoles: ['航空电子', '控制', '导航', '可靠性', '软件开发'], locations: ['上海', '西安'], audienceTags: [], entryExperience: '民航电子国企，岗位稳定，适合航电、控制、通信和软件方向。' }),
  entry('航空工业雷达所', '航空航天 军工 雷达 校招', '', { industry: '航空航天/雷达/军工', recruitmentRoles: ['雷达算法', '通信工程', '电子', '控制', '软件'], locations: ['无锡', '成都', '北京'], audienceTags: [], entryExperience: '机载雷达国企研究所，多城市，技术门槛高，福利稳定。' }),
  entry('航空工业直升机所', '航空航天 军工 直升机 校招', '', { industry: '航空航天/直升机', recruitmentRoles: ['机械', '飞行器', '导航', '控制', '软件'], locations: ['天津', '景德镇'], audienceTags: [], entryExperience: '直升机研发国企，总体设计门槛高，适合航空、机械、控制方向。' }),
  entry('航天科工二院', '航空航天 军工 防务 校招', '', { industry: '航空航天/防务', recruitmentRoles: ['防空导弹', '计算机', '电子', '通信', '自动化'], locations: ['北京', '成都', '西安', '武汉', '南京', '无锡', '长沙', '深圳', '柳州'], audienceTags: [], entryExperience: '航天防务国企，多城市，研发门槛高，稳定性强。' }),
  entry('碳一新能源', '新能源 电力 电池 校招', '', { industry: '新能源/锂电池', recruitmentRoles: ['研发', '应用工程', '生产储干', '品质', '设备', 'EHS'], locations: ['安庆', '衢州', '昭通', '青岛', '深圳', '池州', '杭州'], audienceTags: ['本科友好', '双非友好'], entryExperience: '新能源材料企业，生产和研发岗位多，部分岗位需倒班，城市选择多。' }),
  entry('中广核集团', '央国企 新能源 电力 核电 校招', '', { industry: '核电/新能源发电', recruitmentRoles: ['运行', '维修', '工程', '设计研发', '技术支持', '职能'], locations: ['深圳', '阳江', '惠州', '台山', '福建宁德', '浙江苍南', '广西防城港'], audienceTags: ['本科友好'], entryExperience: '核电央企，多基地，稳定性强，运行维修可能倒班，安全要求高。' }),
  entry('中南电力', '央国企 新能源 电力 设计院 校招', '', { industry: '电力设计/工程咨询', recruitmentRoles: ['电气工程', '土木建筑', '能源动力', '水利工程', '自动化'], locations: ['武汉'], audienceTags: ['本科友好'], entryExperience: '电力设计院国企，武汉为主，设计岗竞争较强，稳定性较好。' }),
  entry('汉缆股份', '新能源 电力 电缆 校招', '', { industry: '电缆/电线制造', recruitmentRoles: ['高端研发', '电缆研发', '工艺', '质量', '销售'], locations: ['崂山', '淄博', '青岛'], audienceTags: ['本科友好', '双非友好'], entryExperience: '电缆制造企业，研发、制造、销售岗位都有，青岛生活成本适中。' }),
  entry('四方股份', '新能源 电力 自动化 校招', '', { industry: '电力自动化/继电保护', recruitmentRoles: ['技术研发', '工程技术', '市场营销', '企业管理'], locations: ['北京', '深圳', '武汉', '南京', '西安', '湖州', '保定'], audienceTags: ['本科友好', '双非友好'], entryExperience: '电力自动化企业，多城市，工程和市场岗位较友好，行业稳定。' }),
  entry('TYT泰永长征', '新能源 电力 低压电器 校招', '', { industry: '低压电器/智能配电', recruitmentRoles: ['销售工程师', '嵌入式软件', '结构工程师', '解决方案工程师'], locations: ['深圳', '全国'], audienceTags: ['本科友好', '双非友好'], entryExperience: '低压电器企业，全国多地派驻，销售和研发岗位都有。' }),
  entry('锐捷智能', '机械装备 工业自动化 校招', '', { industry: '智能装备/工业自动化', recruitmentRoles: ['硬件工程师', '软件工程师', '销售工程师'], locations: ['青岛'], audienceTags: ['本科友好', '双非友好'], entryExperience: '智能装备企业，青岛岗位，研发和销售岗位适合工程背景。' }),
  entry('新界泵业', '机械装备 工业自动化 校招', '', { industry: '水泵/流体机械', recruitmentRoles: ['营销类', '技术类', '制造类', '电商类', '质量类'], locations: ['台州', '杭州', '宿迁', '全国'], audienceTags: ['本科友好', '双非友好'], entryExperience: '水泵制造企业，岗位类型全，制造和营销岗位友好。' }),
  entry('伟创电气', '机械装备 工业自动化 校招', '', { industry: '变频器/伺服驱动', recruitmentRoles: ['算法', '软件', '硬件', '结构', '测试', '工艺'], locations: ['苏州', '西安', '深圳'], audienceTags: ['本科友好', '双非友好'], entryExperience: '电气传动企业，硬件、软件、测试和工艺岗位较友好，多城市可选。' }),
  entry('徐工', '机械装备 工业自动化 校招', '', { industry: '工程机械/重型装备', recruitmentRoles: ['工程机械', '车辆工程', '人工智能', '市场营销', '国际贸易'], locations: ['徐州', '成都', '沈阳', '乌鲁木齐', '武汉', '西安', '南京', '雄安', '广州'], audienceTags: ['本科友好', '双非友好'], entryExperience: '工程机械龙头国企，城市和海外机会多，制造技术岗较友好。' }),
  entry('福船一帆', '机械装备 工业自动化 船舶制造 校招', '', { industry: '船舶制造/钢结构', recruitmentRoles: ['机械工程', '焊接技术', '过程控制', '机电工程', '市场营销'], locations: ['福建漳州'], audienceTags: ['本科友好', '双非友好'], entryExperience: '船舶制造企业，制造为主，工艺、技术和营销岗位较友好，漳州生活成本低。' }),
  entry('长陆智造', '机械装备 工业自动化 智能装备 校招', '', { industry: '工业自动化/智能装备', recruitmentRoles: ['嵌入式软件', '硬件研发', '上位机软件', '电气工程师', '机械设计'], locations: ['合肥'], audienceTags: ['本科友好', '双非友好'], entryExperience: '工业自动化企业，研发和制造并重，合肥生活成本低，成长节奏较快。' }),
  entry('德力佳', '机械装备 工业自动化 传动设备 校招', '', { industry: '齿轮箱/传动设备', recruitmentRoles: ['机械工程师', '工艺工程师', '质量工程师', '电气设备工程师', '采购工程师'], locations: ['无锡'], audienceTags: ['本科友好', '双非友好'], entryExperience: '齿轮箱传动企业，无锡制造和技术岗位多，适合机械、电气、质量方向。' }),
  entry('沃德精密', '机械装备 工业自动化 数控加工 校招', '', { industry: '精密制造/数控加工', recruitmentRoles: ['数控技术员', '检测技术员', '售后技术员'], locations: ['东莞'], audienceTags: ['专科友好', '本科友好', '双非友好'], entryExperience: '精密制造企业，技术成长路径清晰，门槛较低，适合想走技能路线的同学。' }),
  entry('金冠电气', '机械装备 工业自动化 电气设备 校招', '', { industry: '电气设备/避雷器', recruitmentRoles: ['储备干部', '电气技术工程师', '销售工程师', '工业工程师', '质量工程师'], locations: ['南阳'], audienceTags: ['本科友好', '双非友好'], entryExperience: '电气设备企业，制造、技术和生产岗位多，南阳生活成本低。' }),
  entry('中铁广州局城建公司', '央国企 建筑 工程基建 校招', '', { industry: '房建/市政工程', recruitmentRoles: ['土建', '机械电气', '工程管理', '财务会计', '综合管理'], locations: ['广州', '全国'], audienceTags: ['本科友好', '双非友好'], entryExperience: '建筑工程国企，施工为主，需驻项目现场，稳定性较好。' }),
  entry('中铁五局', '央国企 建筑 工程基建 校招', '', { industry: '铁路/公路/市政工程', recruitmentRoles: ['土木', '交通', '水利', '测绘', '安全', '工程管理', '物流管理'], locations: ['长沙', '衡阳', '成都', '重庆', '贵阳', '广州', '东莞', '全国'], audienceTags: ['本科友好', '双非友好'], entryExperience: '铁路工程央企，多城市和全国项目，施工为主，物流管理岗位也可关注。' }),
  entry('中铁二局', '央国企 建筑 工程基建 校招', '', { industry: '铁路/公路/房建工程', recruitmentRoles: ['工程技术', '安全质量', '工程经济', '试验管理', '物资机械', '财务管理'], locations: ['贵阳', '成都', '深圳', '西安', '广州', '上海', '青岛', '雄安', '无锡', '杭州', '乌鲁木齐', '郑州', '长沙', '武汉', '北京'], audienceTags: ['本科友好', '双非友好'], entryExperience: '铁路工程央企，施工为主，多城市可选，稳定性强但可能驻项目。' }),
  entry('中建八局', '央国企 建筑 工程基建 校招', '', { industry: '房建/基建/新能源', recruitmentRoles: ['房建', '基础设施', '水利水电', '新能源', '投资运营', '建筑设计'], locations: ['全国'], audienceTags: ['本科友好', '双非友好'], entryExperience: '建筑工程央企，平台大，施工、投资和设计岗位都有。' }),
  entry('佳农水果集团', '快消 零售 食品 生鲜 校招', '', { industry: '水果进口/生鲜零售', recruitmentRoles: ['采购管培', '质检', '销售', '国际采购', '库管'], locations: ['上海'], audienceTags: ['本科友好', '双非友好'], entryExperience: '生鲜进口企业，采购和销售岗位多，上海生活成本高，行业较特殊。' }),
  entry('纽达投资', '金融 证券 基金 量化 校招', '', { industry: '量化投资/私募基金', recruitmentRoles: ['量化研究员', '系统开发工程师', '新媒体运营'], locations: ['深圳'], audienceTags: [], entryExperience: '量化私募，硕士起步较多，投研门槛高，深圳节奏快。' }),
  entry('大道投资', '金融 证券 基金 量化 校招', '', { industry: '量化投资/私募基金', recruitmentRoles: ['量化研究员', '机器学习研究员', '量化开发工程师'], locations: ['深圳'], audienceTags: [], entryExperience: '量化私募，岗位偏投研和开发，学历门槛高，深圳生活成本高。' }),
  entry('上海姚泾河私募基金管理有限公司', '金融 证券 基金 私募 校招', '', { industry: '私募股权投资/资产管理', recruitmentRoles: ['量化研究员', '量化开发工程师', '数据开发', '主观研究员', 'AI Agent开发'], locations: ['北京', '上海'], audienceTags: [], entryExperience: '私募股权企业，北京和上海岗位，投研门槛高，27/28届可关注。' }),
  entry('保银私募', '金融 证券 基金 私募 实习', '', { industry: '私募基金/资产管理', recruitmentRoles: ['秋季实习生'], locations: ['上海'], audienceTags: [], entryExperience: '私募实习岗位，上海为主，门槛较高，适合金融、经济、数学和计算机背景。' }),
  entry('皓兴科技', '金融 证券 基金 量化 校招', '', { industry: '量化投资/金融科技', recruitmentRoles: ['量化研究员'], locations: ['上海'], audienceTags: [], entryExperience: '量化金融科技企业，上海岗位，投研门槛较高。' }),
  entry('易方达基金', '金融 证券 基金 公募 校招', '', { industry: '公募基金/资产管理', recruitmentRoles: ['投研', '营销', '运营', '子公司岗位', 'AI人才专项'], locations: ['北京', '上海', '广州', '深圳', '香港'], audienceTags: [], entryExperience: '公募基金龙头，多城市，投研门槛极高，平台大福利较好。' }),
  entry('远东通信', '通信 网络设备 央国企 校招', '', { industry: '通信设备/应急通信', recruitmentRoles: ['协议栈开发', '嵌入式开发', '射频开发', '算法开发', '项目经理'], locations: ['石家庄'], audienceTags: ['本科友好'], entryExperience: '通信设备国企，石家庄岗位，研发和技术支持方向稳定。' }),
  entry('TP-Link联洲', '通信 网络设备 校招', '', { industry: '路由器/网络通信设备', recruitmentRoles: ['国际业务管理培训生'], locations: ['深圳', '海外'], audienceTags: ['本科友好', '双非友好'], entryExperience: '网络设备企业，深圳和海外岗位，国际业务管培生专业限制少。' }),
  entry('星逻智能', '智能硬件 机器人 无人机 校招', '', { industry: '无人机/智能巡检', recruitmentRoles: ['研发', '算法', '产品', '营销', '设计'], locations: ['苏州', '上海', '南京'], audienceTags: ['本科友好', '双非友好'], entryExperience: '无人机智能巡检企业，多城市，研发、营销和职能岗位较友好。' }),
  entry('跨维智能', '智能硬件 机器人 AI 校招', '', { industry: '具身智能/AI机器人', recruitmentRoles: ['具身智能算法', '强化学习算法', 'AI视觉算法', '应用开发', '产品经理'], locations: ['深圳'], audienceTags: ['本科友好'], entryExperience: '具身智能初创，深圳岗位，算法门槛高，产品和管培岗可投。' }),
  entry('达坦能源科技', '化工 石油 AI 校招', '', { industry: '油气技术/智能钻井', recruitmentRoles: ['AI工程师', '模型轻量化', '智能导向工程师', '行业大模型落地', '通信工程师'], locations: ['上海', '成都', '德阳', '杭州'], audienceTags: ['本科友好'], entryExperience: '油气智能科技合资企业，多城市，研发和技术岗有特色。' }),
  entry('中远海运', '央国企 航运 物流 校招', '', { industry: '航运/港口/物流', recruitmentRoles: ['船舶驾驶', '轮机管理', '船舶电子电气', '物流管理'], locations: ['北京', '天津', '大连', '上海', '青岛', '广州', '深圳'], audienceTags: ['本科友好', '双非友好'], entryExperience: '航运央企，多港口岗位，航海类对口，物流管理也可关注。' }),
  entry('齐齐熊', '服装 纺织 电商 校招', '', { industry: '童装/电商服装', recruitmentRoles: ['新媒体运营', '商品助理', '服装跟单', '直播中控', '数据分析'], locations: ['合肥'], audienceTags: ['本科友好', '双非友好'], entryExperience: '童装电商企业，运营、直播和职能岗位较多，门槛低，合肥生活成本低。' }),
  entry('乐有家', '房地产 经纪 校招', '', { industry: '房地产经纪/二手房交易', recruitmentRoles: ['营销类', '职能类'], locations: ['深圳', '东莞', '惠州', '中山', '珠海', '江门', '全国'], audienceTags: ['本科友好', '双非友好'], entryExperience: '房产经纪企业，多城市，销售为主，不限专业但压力较大。' }),
  entry('飞博共创', '文化传媒 MCN 校招', '', { industry: '新媒体/MCN/内容营销', recruitmentRoles: ['文案策划', 'AE助理', '签约经纪人', '商务', 'AI全栈', 'AI产品'], locations: ['厦门', '上海'], audienceTags: ['本科友好', '双非友好'], entryExperience: '新媒体MCN企业，内容和商务岗位多，厦门生活成本适中。' }),
  entry('晓禾教育', '教育 K12 校招', '', { industry: 'K12教育培训/在线教育', recruitmentRoles: ['中小学教师', '高中教师', '竞赛教练'], locations: ['武汉', '郑州', '襄阳', '宜昌'], audienceTags: ['本科友好', '双非友好'], entryExperience: 'K12教培企业，多城市，教师岗位为主，需要教师资格证。' }),
  entry('成都社区招聘', '政府 社区 基层治理 校招', '', { industry: '基层社会治理/社区管理', recruitmentRoles: ['实习生', '全职社工'], locations: ['成都'], audienceTags: ['本科友好', '双非友好'], entryExperience: '社区工作者岗位，门槛低，稳定性较好，适合求稳的同学。' }),
  entry('永卓控股', '多元化 投资集团 制造 校招', '', { industry: '钢铁/制造/船舶/投资多元化', recruitmentRoles: ['工艺研发', '智能制造', '船舶制造', '工程建设', '财经投资', '运营管理'], locations: ['苏州', '连云港', '上海'], audienceTags: ['本科友好', '双非友好'], entryExperience: '多元化民营集团，制造和投资岗位都有，多城市可选。' }),
  entry('中国电科三十六所', '央国企 科研院所 通信 电子 校招', '', { industry: '通信技术/电子信息科研', recruitmentRoles: ['通信技术', '计算机软件', '共性技术', '管培生'], locations: ['嘉兴', '上海', '杭州'], audienceTags: [], entryExperience: '电子科技央企研究所，硕士起步较多，科研门槛高，稳定性好。' }),
];
